; PlatformIO Project Configuration
; AIoT Wearable Patient Remote Monitoring System - ESP8266 NodeMCU

[env:nodemcu]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_speed = 115200
upload_speed = 921600

lib_deps =
    adafruit/DHT sensor library@^1.4.6
    adafruit/Adafruit Unified Sensor@^1.1.14
    knolleary/PubSubClient@^2.8
    bblanchon/ArduinoJson@^7.0.4
    sparkfun/SparkFun MAX3010x Pulse and Proximity Sensor Library@^1.1.2

build_flags =
    -D WOKWI_SIM=1
    -D MQTT_MAX_PACKET_SIZE=512
